### ISSUE TITLE
при заходе на сервер вылетает игра

### ISSUE THREAD

**Issue by ruuqwi132** [kitovoi111/Create-Server#16]
я ртпшнулся в какую-то деревню и рядом с ней был гигантский приват, я повернул камеру в его сторону и весь майн завис и вылетел, при заходе на сервер пишет *прогрузка территории* и ничего не происходит, ник ruuqwi135

**Comment by kitovoi111** [comment]
Пожалуйста, попробуйте обновить видеодрайвера, если это не поможет - скиньте краш лог.
