### ISSUE TITLE
Жопа на сервере Indastrial Craft 2 1.19.2

### ISSUE THREAD

**Issue by neJIbmeHbYT** [kitovoi111/Create-Server#17]
Игрок с ником DoctorGrom каждый раз включает лаг машину, из за чего начинает лагать сервер, проседает ТПС, блоки не ломаются, процессы не идут. Всячески портит игру и впечатления от нее. Сервер вылетает каждые 5-10 минут. Пожалуйста, помогите, мы просто хотим нормально играть, а не страдать от лагов и вылетов.

**Comment by neJIbmeHbYT** [comment]
Прошу прощение, ник чуть другой, DocktorGrom

**Comment by kitovoi111** [comment]
Будет проведено более детальное расследование данного инцидента, на данный момент игрок заблокирован за багоюз и создание лаг машин на сервере.
