### ISSUE TITLE
Пропали предметы после отката на Create 1.19.2

### ISSUE THREAD

**Issue by kilmencube** [kitovoi111/Create-Server#18]
Моему другу нанес урон игрок, из-за чего на нем появился PVP-Режим, я убил этого игрока. Произошел откат(сервер выключился), из-за этого друг умер и вещи пропали, и у него их не было, так как случился откат, то все что мы делали за это время откатилось. НО. Мой друг умер прямо перед откатом, то есть он должен был остаться с вещами, но у него их не было, и на земле тоже пусто. Мы хотим чтобы вы как-нибудь решили эту проблему и вернули моему другу вещи. Его ник emetery_ . Это произошло 06.07.2024 в ~18:30.
Я знаю что это произошло не по нашей ошибке, сервер сильно залагал из-за этого его перезагрузили и откатили.

**Comment by kilmencube** [comment]
Так же хочу добавить что если бы не откат, то мы бы просто забрали вещи спокойно, так что это не наша вина

**Comment by kitovoi111** [comment]
Исправлено.
