### ISSUE TITLE
Вылетает кристаликс креейт 1.19.2

### ISSUE THREAD

**Issue by bioker-b** [kitovoi111/Create-Server#20]
Сегодня утром я зашёл на кристаликс 1.19.2 и у меня после каждого захода начал вылетать кристаликс

Uploading InShot_20240710_095452651.mp4…

**Comment by kitovoi111** [comment]
Скиньте краш лог

**Comment by kitovoi111** [comment]
Попробуйте обновить видео драйвера, а так же удалить папку с клиентом.
