### ISSUE TITLE
Та же история на сервере IndastrialCraft 1.19.2

### ISSUE THREAD

**Issue by neJIbmeHbYT** [kitovoi111/Create-Server#22]
Я не пойму, почему сервер кладут совсем разными способами, а на это не всегда обращают внимание. Не хочу оскорбить или обидеть разрабов, но опять кладут сервер и лаги неимоверные, тпс садится до 1, в этот раз лаги вызывают прогрузкой большого количества чанков, что кладет сервер за считаные минуты, оправдывая это тем, что "скоро вайп" и говорят, что смысла играть нету из за вайпа. В частности сейчас кладет сервер игрок tryam_hello и еще один игрок (личность пока что неизвестна). Почему я захожу с желанием спокойно поиграть и расслабится, а получаю жуткие лаги, жалкие оправдания со стороны виновников, постоянные вылеты и потерянные вещи из за смерти в аду из за лагов?????

**Comment by kitovoi111** [comment]
Как было сказано - сервер будет переделан и выпущен релиз на выходных.
