### ISSUE TITLE
Бан по причине "Сын дерьма с читами"

### ISSUE THREAD

**Issue by madao644** [kitovoi111/Create-Server#24]
Здравствуйте, на сервере IndustialCraft 1.19.2, забанили через 2 часа после вайпа, по причине "Сын дерьма с читами". Хотел хотя-бы узнать повод, почему меня приняли за читера. Было бы славно, если бы разбанили, ведь читы не использую. (ник: madao_)

**Comment by kitovoi111** [comment]
Здравствуйте. Такая причина ставится только самым ушлым и никчемным читерам на проекте, к которым нет никакого уважения, **пожалуйста, ознакомьтесь с предоставленной ниже информацией**.
![image](https://github.com/user-attachments/assets/d1e5c991-e0f9-4a07-b5ea-96c0ab11470d)
