### ISSUE TITLE
Забанили по причине "Хранение Дюпа"

### ISSUE THREAD

**Issue by VerdantLight** [kitovoi111/Create-Server#25]
как я понимаю эти "дюпанные вещи" раздавал игрок nikitf87. вопрос откуда мне знать что эти вещи дюпанные?

**Comment by stepa3385** [comment]
блять зашол на сервер поиграть по кд раздачи вы чо там слепые нахуй мы не ебём какие там дюп не дюп но факт того что админ подлетел и хуйнул всё ядеркой остаёться фактом вы баните людей не зачто
