### ISSUE TITLE
бан за лутание дюп вищей на раздаче 

### ISSUE THREAD

**Issue by stepa3385** [kitovoi111/Create-Server#26]
люди раздают дюп вещи и из за этого просто за то что ты в погоне за холявой забрал их к тебе подлетает админ либо забирает все вещи либо авзрывает всю базу

**Comment by VerdantLight** [comment]
![Uploading Jq1Koy1ejRw.jpg…]()

**Comment by VerdantLight** [comment]
бам бам бам мы стреляем по хохлам
![Uploading Jq1Koy1ejRw.jpg…]()

**Comment by stepa3385** [comment]
так заберите дюп вещи и забаньте людей раздающих дюп вещи я их знаю как минимум 2 
зачем взрывать я помню как к дюперу админ подлетел сказал больше так не делай и тепнулся а обычным людям подобравшие эти вещи херачат базу и банят ну сука вы блять ебашите людей которые на раздаче лутают дюп вещи а дюперам просто говорите так не делай как блять мне добиться такого через постель или как

**Comment by kitovoi111** [comment]
Дюп предметы очищаются со временем.
