### ISSUE TITLE
Жб на дитхела

### ISSUE THREAD

**Issue by Chebureckpavyk** [kitovoi111/Create-Server#28]
Меня убили с 1 тыки дружки дитхела и он начал их защищять и сказал это зелька силы 2 просто и послал и все! Он открывает двери в приватах выдает людям спектаторы и в чат пишет кто за мой бан + в чат вот ссылка. https://youtu.be/4OccBf-2OBA?si=6OoOQAbWEk3W-g4h , https://youtu.be/ycAb4R1VBnU?si=tsfXcZcOEnLXJcSr
https://youtu.be/Nu8yn7ogFD4?si=_m8DzjQw_JsWnQ76,
https://youtu.be/TrjHxke7tw0?si=951_vv0KSMPcixax, 
https://youtu.be/nhCb9DZg_ew?si=WWo9dRY_d3nEISdT ник Vadim_11

**Comment by kitovoi111** [comment]
Благодарю за обращение. Данный игрок снят с поста администрации.
