### ISSUE TITLE
Копье вымирания не тикает если его кинуть дальше диапазона прогрузки игрока

### ISSUE THREAD

**Issue by Gucyqe** [kitovoi111/Create-Server#30]
Я кинул копье вымирания зачарованное ахереное и оно тупо исчезло я его минут 20 искал везде оно просто пропало, я понимаю если бы кинул его куда то в бездну в энде и тд но это была тупо поляна там не было каких нибудь воронок вообще ничего куда оно могло попасть оно тупо исчезло и пропало

**Comment by kitovoi111** [comment]
Будет исправлено.

**Comment by Gucyqe** [comment]
> Будет исправлено.
 а мне че делать оно ахуенное было я ради него весь лут проебал на этом боссе как мне его вернуть оно было зачарованно по максиму

**Comment by kitovoi111** [comment]
> > Будет исправлено.
> > а мне че делать оно ахуенное было я ради него весь лут проебал на этом боссе как мне его вернуть оно было зачарованно по максиму

Вы кидали его в чужой приват? или просто в мире без привата?

**Comment by Gucyqe** [comment]
просто в мире без привата

**Comment by kitovoi111** [comment]
Я сообщу, как только это будет исправлено.

**Comment by stepa3385** [comment]
здравствуйте каким то чудом ко мне тепнулся человек и это был не админ расприватил чанки с сундуками и забрал все вещи большая просьба помочь мне с этой проблемой и вернуть ресурсы также человек который это сделал евляеться дюпером и раздаёт дюп вещи прошу вас отдать моё рг и вернуть ресурсы никней человека сделавшего это angell123 блять только попробуйте сказать 2 раз что это хуйня всё нормально и ангела не забанят ник его тимейта c0mba

**Comment by kitovoi111** [comment]
Исправлено.
