### ISSUE TITLE
Снесли пол дома землёй в приваченой тере!

### ISSUE THREAD

**Issue by Trolleg322** [kitovoi111/Create-Server#31]
Пару дней отсутствовал на серваке, сейчас зашел, а у меня по всей тере огромные кубы из земли, части дома нет половины сундуков нет, поезд укатили в другую часть теры... сервер Create ник: Trolleg

**Comment by stepa3385** [comment]
здравствуйте каким то чудом ко мне тепнулся человек и это был не админ расприватил чанки с сундуками и забрал все вещи большая просьба помочь мне с этой проблемой и вернуть ресурсы также человек который это сделал евляеться дюпером и раздаёт дюп вещи прошу вас отдать моё рг и вернуть ресурсы никней человека сделавшего это angell123 блять только попробуйте сказать 2 раз что это хуйня всё нормально и ангела не забанят ник его тимейта c0mba

**Comment by stepa3385** [comment]
здравствуйте каким то чудом ко мне тепнулся человек и это был не админ расприватил чанки с сундуками и забрал все вещи большая просьба помочь мне с этой проблемой и вернуть ресурсы также человек который это сделал евляеться дюпером и раздаёт дюп вещи прошу вас отдать моё рг и вернуть ресурсы никней человека сделавшего это angell123 блять только попробуйте сказать 2 раз что это хуйня всё нормально и ангела не забанят ник его тимейта c0mba

**Comment by kitovoi111** [comment]
Ваш регион возможно был удален из за неактивности или же Ваши тиммейты Вас подставили.
