### ISSUE TITLE
IC2 любые сущности которые можно кинуть пропадают при попадании в чужой рг

### ISSUE THREAD

**Issue by pepepeee** [kitovoi111/Create-Server#32]
кидаю трезубец, пёрл, яйцо, снежок и т.п. и они просто пропадают, даже не возвращаются в инвентарь и пишет вот это
![image](https://github.com/user-attachments/assets/6f32807d-6df7-4b1f-97f4-b1028d6c788d)

**Comment by stepa3385** [comment]
здравствуйте каким то чудом ко мне тепнулся человек и это был не админ расприватил чанки с сундуками и забрал все вещи большая просьба помочь мне с этой проблемой и вернуть ресурсы также человек который это сделал евляеться дюпером и раздаёт дюп вещи прошу вас отдать моё рг и вернуть ресурсы никней человека сделавшего это angell123 блять только попробуйте сказать 2 раз что это хуйня всё нормально и ангела не забанят ник его тимейта c0mba

**Comment by kitovoi111** [comment]
Исправлено
