### ISSUE TITLE
Баг с копьем вымирания

### ISSUE THREAD

**Issue by kefanix** [kitovoi111/Create-Server#33]
Create 1.19.2 / Пропадает копье вымирания, при попадании в приват любого чужого игрока. Я кинул уже 2 копья вымирания с фул зачарами и так же их просрал. Не работало даже прокликнуть по слоту, провести по всему инвентарю, перезаход на сервер. Копье просто проподало и не возвращалось. Баг работает не всегда, есть какой то шанс проподания...

**Comment by Gucyqe** [comment]
Тоже самое только блять я не в чужое кидал

**Comment by kitovoi111** [comment]
Я сообщу, как только это будет исправлено.

**Comment by stepa3385** [comment]
здравствуйте каким то чудом ко мне тепнулся человек и это был не админ расприватил чанки с сундуками и забрал все вещи большая просьба помочь мне с этой проблемой и вернуть ресурсы также человек который это сделал евляеться дюпером и раздаёт дюп вещи прошу вас отдать моё рг и вернуть ресурсы никней человека сделавшего это angell123 блять только попробуйте сказать 2 раз что это хуйня всё нормально и ангела не забанят ник его тимейта c0mba

**Comment by kitovoi111** [comment]
Исправлено
