### ISSUE TITLE
варданы на всей базе, загрифели нас челы

### ISSUE THREAD

**Issue by 45285** [kitovoi111/Create-Server#34]
![image](https://github.com/user-attachments/assets/5d8ff7dd-ee27-49d3-902f-3931bf12e0f9)

**Comment by 45285** [comment]
из за них я джет пак потерял мне его возместят?

**Comment by 45285** [comment]
вернут ли меч другу? вернут ли ему броню? вернут ли все потерянные вещи? забанят ли нарушителей?

**Comment by kitovoi111** [comment]
> вернут ли меч другу? вернут ли ему броню? вернут ли все потерянные вещи? забанят ли нарушителей?

Что нарушили данные игроки?

**Comment by stepa3385** [comment]
здравствуйте каким то чудом ко мне тепнулся человек и это был не админ расприватил чанки с сундуками и забрал все вещи большая просьба помочь мне с этой проблемой и вернуть ресурсы также человек который это сделал евляеться дюпером и раздаёт дюп вещи прошу вас отдать моё рг и вернуть ресурсы никней человека сделавшего это angell123 блять только попробуйте сказать 2 раз что это хуйня всё нормально и ангела не забанят ник его тимейта c0mba

**Comment by kitovoi111** [comment]
Не считается багом.
