### ISSUE TITLE
Будут ли slim скины на create 1.19.2?

### ISSUE THREAD

**Issue by kefanix** [kitovoi111/Create-Server#37]
Давно хотел что бы на креэйт добавили слим скины( с тонкими руками ) Потому что большие руки во многих скинах выглядят ущербно.. Хотелось бы что бы были слим скины как на минииграх.

**Comment by stepa3385** [comment]
здравствуйте каким то чудом ко мне тепнулся человек и это был не админ расприватил чанки с сундуками и забрал все вещи большая просьба помочь мне с этой проблемой и вернуть ресурсы также человек который это сделал евляеться дюпером и раздаёт дюп вещи прошу вас отдать моё рг и вернуть ресурсы никней человека сделавшего это angell123 блять только попробуйте сказать 2 раз что это хуйня всё нормально и ангела не забанят ник его тимейта c0mba

**Comment by kitovoi111** [comment]
Неизвестно. На данный момент мы такой информацией не владеем.
