### ISSUE TITLE
у меня слетел рг и мою базу заприватил другой

### ISSUE THREAD

**Issue by cucl1221** [kitovoi111/Create-Server#39]
у меня слетел рг и мою базу заприватил другой игрок

**Comment by stepa3385** [comment]
здравствуйте каким то чудом ко мне тепнулся человек и это был не админ расприватил чанки с сундуками и забрал все вещи большая просьба помочь мне с этой проблемой и вернуть ресурсы также человек который это сделал евляеться дюпером и раздаёт дюп вещи прошу вас отдать моё рг и вернуть ресурсы никней человека сделавшего это angell123

**Comment by kitovoi111** [comment]
Если Вы не заходили в игру более 14-и дней - регион автоматически удаляется.
