### ISSUE TITLE
Уже который раз теряю вещи навсегда

### ISSUE THREAD

**Issue by Sendgrish32** [kitovoi111/Create-Server#40]
Я построил лифт  на своей базе и когда спускался дальше бурить шахту я упал и оставил вещи, вроде бы они должны там остаться, но не на кристаликсе, они просто пропали и остался только опыт, из-за этого бага я теряю уже 2 алмазную кирку, прошу исправить.

**Comment by kitovoi111** [comment]
Вещи не могли пропасть сами по себе. Возможно их забрал игрок или Вы слишком долго искали их. Обычное время исчезновения предметов на земле: 5 минут.
