### ISSUE TITLE
У ДРУГА БАЗА - ЧАНК БАНЫ

### ISSUE THREAD

**Issue by JDH993-blip** [kitovoi111/Create-Server#42]
У моего друга Terrka120 (вроде так) на базе произошел баг и его база стала чанк баном при чем не падет фпс просто вылетает игра итог -ресы надеюсь исправят а то жалко же (

**Comment by kitovoi111** [comment]
Сервер Create ? Что именно происходит на его базе?

**Comment by DarkLordVentkram** [comment]
x

**Comment by JDH993-blip** [comment]
Я временно не мог заходить на сервер  по Create но сегодня его база починилась больше не банит

**Comment by kitovoi111** [comment]
Исправлено. Если ошибка повториться - отправьте краш лог с клиента.
