### ISSUE TITLE
Вардены на базе

### ISSUE THREAD

**Issue by DarkLordVentkram** [kitovoi111/Create-Server#43]
МНЕ ЕБАШАТ 24/7 ВАРДЕНОВ НА БАЗУ amaterasooo и  _TEAM_Ghoul_ ПРОСЬБА ДАТЬ ИМ ПО ЕБАЛУ ВОТ ПРУФ - https://imgur.com/a/cgaqZpB

**Comment by Anonim228355** [comment]
А то что ты сам попросил себе заприватить вокруг базы чтоб расширится и сам себе же заспавнил варденов чтоб нас подставить это ты забыл уточнить как я понял

**Comment by DarkLordVentkram** [comment]
ну я ничего не просил и не просил око искателя на меня клеить и таргетить везде

**Comment by Anonim228355** [comment]
У тебя репутация дерьма на сервере чему тут удивлятса

**Comment by DarkLordVentkram** [comment]
Норм у меня reputation

**Comment by kitovoi111** [comment]
Не считается багом.
