### ISSUE TITLE
ЧТО ЗА ХУ*НЯ

### ISSUE THREAD

**Issue by Slake-1** [kitovoi111/Create-Server#48]
Я РАСПРИВАТИЛ 2 ЧАНКА С РЕСАМИ НА ВРЕМЯ И НЕ МОГУ ЗАПРИВАТИТЬ ОБРАНО ХОТЯ Я НЕЧЕГО НЕ ДЕЛАЛ ДРУГОВО МОЙ НИК Slake_1

**Comment by kitovoi111** [comment]
Приваты были урезаны для игроков. Теперь максимум 9 чанков.
