### ISSUE TITLE
Гриф буром.

### ISSUE THREAD

**Issue by kefanix** [kitovoi111/Create-Server#52]
Я поставил бур в своем рг, но когда я его собрал у меня крашнуло майнкрафт, когда я зашел увидел как бур толкают в моем привате, и нету половины дома, ресы почти все остались. Ник игрока wolmond2012. Мой ник - KrOkODil4ik_. Также данный игрок пользуется багом на сете тьмы, и летает и днем и ночью бесконечно.

**Comment by kitovoi111** [comment]
Гриферство не запрещено. Тем более это было по Вашей вине.
