### ISSUE TITLE
Реактивный шахтер

### ISSUE THREAD

**Issue by Bataysk** [kitovoi111/Create-Server#9]
У меня в прямом смысле завис в воздухе шахтер и результатов никаких. В шахтере был энергокрисал на 7,5млн EU, сканер ценности руд большой дальности на 10 блоков, утилизатор, лазер, пульт и модуль генератора камня. Так же полными были резервуар и шахтерская труба и итог всего в воздухе...
![Снимок экрана 2024-06-29 045902](https://github.com/kitovoi111/Create-Server/assets/174160409/6c914c3c-f3ca-4b73-be1d-8d914788373d)

**Comment by rayle777** [comment]
такая же проблема

**Comment by rayle777** [comment]
улетел в чужой приват с продвинутым буром

**Comment by Bataysk** [comment]
> улетел в чужой приват с продвинутым буром

вроде как в него достаточно положить лазер, ты пульт делал второй?

**Comment by kitovoi111** [comment]
Исправлено.
